### ISSUE TITLE
Feature Idea: Display info box while operating with a tree harvester

### ISSUE THREAD

**Issue by Timmeey86** [Timmeey86/FS22_TreeValueInfo#2]

**Comment by vitalii2011** [comment]
"Info box" is not displayed with activated
Wood Harvester Controls https://www.farming-simulator.com/mod.php?lang=en&country=ru&mod_id=263015&title=fs2022

**Comment by vitalii2011** [comment]
This is probably not because of the mod, but due to the mechanics of the game, but the logic for determining the quality of logs is strange:
![fsScreen_2024_02_08_13_34_45](https://github.com/Timmeey86/FS22_TreeValueInfo/assets/41552153/9481f4bc-d436-4c35-96b4-34ecc034abe4)
![fsScreen_2024_02_08_13_35_08](https://github.com/Timmeey86/FS22_TreeValueInfo/assets/41552153/34c269a3-ab0b-45cc-b16f-0451c2176f01)
![fsScreen_2024_02_08_13_36_59](https://github.com/Timmeey86/FS22_TreeValueInfo/assets/41552153/606459de-0164-45fc-9a84-47cb1ee5fa82)
![fsScreen_2024_02_08_13_37_27](https://github.com/Timmeey86/FS22_TreeValueInfo/assets/41552153/8eb8a743-a999-40fe-8611-9a1d4f80f0fc)

**Comment by Timmeey86** [comment]
> "Info box" is not displayed with activated Wood Harvester Controls https://www.farming-simulator.com/mod.php?lang=en&country=ru&mod_id=263015&title=fs2022

Alright, I will look into this tonight

**Comment by Timmeey86** [comment]
> This is probably not because of the mod, but due to the mechanics of the game, but the logic for determining the quality of logs is strange:

The game pays you most money for logs which are between 6 and 11m long. If you split a 20m log into two 10m pieces you get way more money

I don't know why Giants made it this way, but my mod tries to at least make this fact more obvious

**Comment by vitalii2011** [comment]
Thanks for clarifying.
On the loading screen of the game, advice appears: ~ “the straighter and longer the log, the higher its price,” - this raised the question. )

**Comment by Timmeey86** [comment]
@vitalii2011 It is as I suspected: Wood harvester system overrides the same method as me, but does not call the existing code, so my code gets skipped completely.
I will have to think about some kind of ugly workaround for this as it's unlikely the other mod will get adapted.

**Comment by vitalii2011** [comment]
- I don't think that the interesting but not simple Wood Harvester Controls are used by many people.
- You can chat with the author of WHC - Jamesxtreme here https://discord.com/channels/928667003835793460/1148672304373567581

**Comment by Timmeey86** [comment]
@vitalii2011 I just uploaded a new version (on GitHub) which should fix this issue

**Comment by vitalii2011** [comment]
1.0.3.1 - no problem. Thank you.
